name: Update README with Rocco
on:
  workflow_dispatch:
  schedule:
    - cron: "45 8 * * *" # Run every day at 12:45 AM PST

permissions:
  contents: write
jobs:
  rocco:
    runs-on: ubuntu-latest
    name: Update README
    steps:
      - uses: petabite/rocco@v1
